### ISSUE TITLE
CT: duplicates are not allowed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-mixed-numbers#2]
```
fractions-mixed-numbers : fuzz : require.js-canvas : run
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
    at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/ObservableArray.js?bust=1535726082664:220:15)
    at BuildingLabModel.removeLastPieceFromShapeGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/BuildingModel.js?bust=1535726082664:243:34)
    at removeLastListener (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/view/BuildingLabScreenView.js?bust=1535726082664:264:22)
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/view/ReturnButton.js?bust=1535726082664:48:9)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/Emitter.js?bust=1535726082664:134:49)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/sun/js/buttons/PushButtonModel.js?bust=1535726082664:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/sun/js/buttons/PushButtonModel.js?bust=1535726082664:88:16)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/Emitter.js?bust=1535726082664:180:49)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/Property.js?bust=1535726082664:304:29)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/Property.js?bust=1535726082664:287:14)
Approximately 8/31/2018, 3:09:16 AM
```

**Comment by KatieWoe** [comment]
@jonathanolson CT issue now shows up as:
```
fractions-mixed-numbers : xss-fuzz : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/phet-core/js/arrayRemove.js?bust=1536579822559:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/game/view/FractionChallengeNode.js?bust=1536579822559:345:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/ObservableArray.js?bust=1536579822559:155:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/ObservableArray.js?bust=1536579822559:195:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/BuildingModel.js?bust=1536579822559:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/Animator.js?bust=1536579822559:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/Animator.js?bust=1536579822559:119:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/ShapePiece.js?bust=1536579822559:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/BuildingModel.js?bust=1536579822559:389:20)
Approximately 9/10/2018, 3:43:46 AM
```

**Comment by jonathanolson** [comment]
I believe these failures should be fixed. Can you verify (or see if they don't happen in CT for a bit?)

**Comment by KatieWoe** [comment]
@jonathanolson the Item not found in Array error showed up yesterday.
```
fractions-mixed-numbers : fuzz : require.js : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/phet-core/js/arrayRemove.js?bust=1540368725902:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/game/view/FractionChallengeNode.js?bust=1540368725902:347:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/axon/js/ObservableArray.js?bust=1540368725902:161:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/axon/js/ObservableArray.js?bust=1540368725902:201:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/BuildingModel.js?bust=1540368725902:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/Animator.js?bust=1540368725902:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/Animator.js?bust=1540368725902:125:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/ShapePiece.js?bust=1540368725902:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/BuildingModel.js?bust=1540368725902:399:20)
id: JO Win10 Chrome
Approximately 10/24/2018, 12:52:11 AM
fractions-mixed-numbers : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/phet-core/js/arrayRemove.js?bust=1540367229532:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/game/view/FractionChallengeNode.js?bust=1540367229532:347:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/axon/js/ObservableArray.js?bust=1540367229532:161:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/axon/js/ObservableArray.js?bust=1540367229532:201:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/BuildingModel.js?bust=1540367229532:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/Animator.js?bust=1540367229532:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/Animator.js?bust=1540367229532:125:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/ShapePiece.js?bust=1540367229532:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540363931154/fractions-common/js/building/model/BuildingModel.js?bust=1540367229532:399:20)
id: JO Win10 Chrome
Approximately 10/24/2018, 12:52:11 AM
```

**Comment by jonathanolson** [comment]
I believe this has been fixed a while ago, can you verify?

**Comment by KatieWoe** [comment]
Doesn't seem to have shown up recently
